name: KayjiSimpleRewardZone
version: 1.0.0
main: me.kayji.simplerewardzone.KayjiSimpleRewardZone
api-version: '1.21'
author: Kayji
softdepend: [FancyHolograms]
folia-supported: true

commands:
  rewardzone:
    description: Quan ly ruong thinh SimpleRewardZone
    usage: /rewardzone
    aliases: [rz, thinh]

permissions:
  rewardzone.admin:
    description: Cho phep quan ly ruong thinh
    default: op
